package com.weavebytes.dogsapp.model;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.weavebytes.dogsapp.model.Dogs;

import com.weavebytes.dogsapp.model.DogsDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dogsDaoConfig;

    private final DogsDao dogsDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dogsDaoConfig = daoConfigMap.get(DogsDao.class).clone();
        dogsDaoConfig.initIdentityScope(type);

        dogsDao = new DogsDao(dogsDaoConfig, this);

        registerDao(Dogs.class, dogsDao);
    }
    
    public void clear() {
        dogsDaoConfig.getIdentityScope().clear();
    }

    public DogsDao getDogsDao() {
        return dogsDao;
    }

}
