package com.weavebytes.dogsapp.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table Dogs.
 */
public class Dogs {

    private Long id;
    private String Name;
    private Integer BirthDate;
    private Integer Weight;
    private Integer Withers;
    private String Breed;
    private String Chip;
    private String Sex;

    public Dogs() {
    }

    public Dogs(Long id) {
        this.id = id;
    }

    public Dogs(Long id, String Name, Integer BirthDate, Integer Weight, Integer Withers, String Breed, String Chip, String Sex) {
        this.id = id;
        this.Name = Name;
        this.BirthDate = BirthDate;
        this.Weight = Weight;
        this.Withers = Withers;
        this.Breed = Breed;
        this.Chip = Chip;
        this.Sex = Sex;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return Name;
    }

    public void setName(String Name) {
        this.Name = Name;
    }

    public Integer getBirthDate() {
        return BirthDate;
    }

    public void setBirthDate(Integer BirthDate) {
        this.BirthDate = BirthDate;
    }

    public Integer getWeight() {
        return Weight;
    }

    public void setWeight(Integer Weight) {
        this.Weight = Weight;
    }

    public Integer getWithers() {
        return Withers;
    }

    public void setWithers(Integer Withers) {
        this.Withers = Withers;
    }

    public String getBreed() {
        return Breed;
    }

    public void setBreed(String Breed) {
        this.Breed = Breed;
    }

    public String getChip() {
        return Chip;
    }

    public void setChip(String Chip) {
        this.Chip = Chip;
    }

    public String getSex() {
        return Sex;
    }

    public void setSex(String Sex) {
        this.Sex = Sex;
    }

}
